resilience4j:
  retry:
    configs:
      default:
        maxAttempts: 5
        waitDuration: 5s
        enableExponentialBackoff: true
        exponentialBackoffMultiplier: 2
        retryExceptions:
          - org.springframework.web.client.ResourceAccessException
          - java.io.IOException
          - org.springframework.web.client.HttpServerErrorException

    instances:
      service1:
        baseConfig: default
      service2:
        baseConfig: default
      service3:
        baseConfig: default
      service4:
        baseConfig: default
      service5:
        baseConfig: default

  circuitbreaker:
    configs:
      default:
        slidingWindowSize: 100
        permittedNumberOfCallsInHalfOpenState: 2
        waitDurationInOpenState: 1s
        failureRateThreshold: 10 # percentage
        eventConsumerBufferSize: 10
        registerHealthIndicator: true
    instances:
      service1:
        baseConfig: default
      service2:
        baseConfig: default
      service3:
        baseConfig: default
      service4:
        baseConfig: default
      service5:
        baseConfig: default



  bulkhead:
    configs:
      default:
        maxConcurrentCalls: 10
    instances:
      service1:
        baseConfig: default
      service2:
        baseConfig: default
      service3:
        baseConfig: default
      service4:
        baseConfig: default
      service5:
        baseConfig: default

  ratelimiter:
    configs:
      default:
        limitForPeriod: 10
        limitRefreshPeriod: 1s
        timeoutDuration: 0
        registerHealthIndicator: true
        eventConsumerBufferSize: 100
    instances:
      service1:
        baseConfig: default
      service2:
        baseConfig: default
      service3:
        baseConfig: default
      service4:
        baseConfig: default
      service5:
        baseConfig: default

  timelimiter:
    configs:
      default:
        timeoutDuration: 2s
        cancelRunningFuture: true
    instances:
      service1:
        baseConfig: default
      service2:
        baseConfig: default
      service3:
        baseConfig: default
      service4:
        baseConfig: default
      service5:
        baseConfig: default
